[build]
  publish = "_site"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  prettyURLs = true
  trailingSlash = true

  [plugins.inputs]
    changeFreq = "daily"
    priority = 0.5